server:
  port: 8083

logging:
  level:
    org.apache.rocketmq: DEBUG
    com.neu.youthpathtalk.post.biz: DEBUG

post:
  cleanup:
    enabled: true                # 是否启用清理任务
    retain-days: 30              # 保留天数（软删除后超过多少天物理删除）
    batch-size: 1000             # 每次删除的最大记录数
    cron: "0 0 3 * * ?"          # 每天凌晨3点执行
  consumer:
    rate:
      record:
        like: 5000

idempotent:
  cleanup:
    enabled: true                # 是否启用清理任务
    retain-days: 7              # 保留天数（软删除后超过多少天物理删除）
    batch-size: 1000             # 每次删除的最大记录数
    cron: "0 0 4 * * ?"          # 每天凌晨3点执行

hotboard:
  time-window-hours: 168   # 7*24
  board-size: 20
  batch-size: 1000
  cron: "0 */10 * * * ?"
  decay-base: 0.95
  weight:
    view: 1.0
    like: 2.0
    comment: 3.0
    favorite: 4.0

spring:
  application:
    name:
      youthpathtalk-post-service
  profiles:
    active: dev
