server:
 port: 8082

idempotent:
 cleanup:
  enabled: true                # 是否启用清理任务
  retain-days: 7              # 保留天数（软删除后超过多少天物理删除）
  batch-size: 1000             # 每次删除的最大记录数
  cron: "0 0 3 * * ?"          # 每天凌晨3点执行

spring:
 application:
  name:
   youthpathtalk-user-service
 profiles:
  active: dev

