server:
  port: 10010

spring:
  application:
    name: gateway
  profiles:
    active: dev

# Sa-Token 配置
sa-token:
  # token 名称->不仅影响 HTTP 请求头（如 Authorization 头），还影响 Redis 中存储的键前缀。
  token-name: Authorization
  # token 前缀->影响HTTP请求头解析:Authorization:Bearer 2922955a-d526-47e9-8ede-bb701f337910
#  token-prefix: Bearer #使用cookie方式无需前缀，如果加了会提前终止，影响从 Cookie 读取
  # Token 有效期（秒）7天
  timeout: 604800
  # Token 临时有效期（指定时间内无操作就过期）
  active-timeout: -1
  # 是否允许同一账号多地登录
  is-concurrent: true
  # 是否共享 Token
  is-share: false
  # Token 风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  is-read-cookie: true          # 默认 true
  is-write-cookie: true         # 写入 Cookie（默认 true）
  cookie:
    path: /                          #默认
    domain: localhost                #默认
    same-site: Lax                   # 或 Strict，防止 CSRF
    secure: false                    # 如果全站 HTTPS，改为 true
    http-only: true                  # 默认就是 true

  # Redis 配置（复用 Spring 的 Redis）
  alone-redis:
    disabled: true  # 使用集成 Redis，不用独立配置

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG